version: "3.8"

services:

  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=biddingApp
    ports:
      - 3307:3306
    volumes:
      - ./db:/var/lib/mysql

  backend:
    container_name: springboot
    image: darshan4163264/spebackend:latest
    depends_on:
      - mysqldb
    ports:
      - 8282:8282
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password

    restart: on-failure
    extra_hosts:
      - "dockerhost:172.21.0.1"

  frontend:
    container_name: reactfrontend
    image: darshan4163264/spefrontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    restart: on-failure

    stdin_open: true
    tty: true
