version: "3.8"

services:

  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=biddingApp
    ports:
      - 3307:3306
    volumes:
      - ./db:/var/lib/mysql

  app:
    image: darshan4163264/spebackend:latest
    depends_on:
      - mysqldb
    build: .
    ports:
      - 8282:8282
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: password

    restart: on-failure

    stdin_open: true
    tty: true